sudo: required

language: go

go:
  - 1.5.3
  - 1.6.3
  - 1.7.3
  - tip

# allow failures only on last version of go.
matrix:
  allow_failures:
    - go: tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
